### ISSUE TITLE
Demo 2 - not show month with multiple events

### ISSUE THREAD

**Issue by infocobrasil** [codrops/Calendario#35]
I find a problem with index2 using multiple events in one day, if you go to next month, then you cannot get back to the month with the multiple events, it will give a error in the console: Uncaught TypeError: Cannot read property 'split' of undefined

**Comment by dougaxe1** [comment]
I think the issue is that `_convertDayArray()` is operating on a reference of `caldata`. It expects an array of objects, but instead gets an HTML string. 

I fixed this by adding a line to `_parseDataToDay()`:
```javascript
_parseDataToDay : function (data, day, other) {
  data = JSON.parse(JSON.stringify(data)); // Create clone of data so we don't overwrite the original
  ...
```

It should be investigated if there is a better way to handle wrapHTML or convertDayArray, but those may involve changing many more lines of code.

**Comment by infocobrasil** [comment]
It work fine with that modification.

Thanks.

**Comment by cycap** [comment]
found the same bug and solved it too with 

```javascript
_convertDayArray: function (dayOrig, date) {
      var day = dayOrig.slice(0); // clone to prevent overwriting content
```
